default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picalica_development

  
test:
  <<: *default
  database: picalica_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: picalica_production
    username: picalica
    password: <%= ENV["PICALICA_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: picalica_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: picalica_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: picalica_production_cable
    migrations_paths: db/cable_migrate